# Generated by Django 6.0.6 on 2026-06-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_rename_assets_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sensor Misaligned / Damaged', 'Sensor Misaligned / Damaged'), ('No Power', 'No Power'), ('Unusual Noise / Vibration', 'Unusual Noise / Vibration'), ('Other', 'Other'), ('HMI / Screen Frozen or Black', 'HMI / Screen Frozen or Black'), ('Calibration Due / Out of Tolerance', 'Calibration Due / Out of Tolerance'), ('Broken Parts / Belt / Chain', 'Broken Parts / Belt / Chain'), ('Fluid Leak / Oil Leak', 'Fluid Leak / Oil Leak'), ('Temperature / Pressure Out of Range', 'Temperature / Pressure Out of Range'), ('Component Jammed / Stuck', 'Component Jammed / Stuck'), ('HVAC / Cleanroom / Utilities', 'HVAC / Cleanroom / Utilities'), ('Safety Issue', 'Safety Issue'), ('Other', 'Other')], max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
