# Generated by Django 6.0.6 on 2026-06-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='ai_priority',
        ),
    ]
