# Generated by Django 6.0.6 on 2026-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_add_done_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
