# Generated by Django 6.0.6 on 2026-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_alter_workorder_done_alter_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='done',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
    ]
