# Generated by Django 6.0.6 on 2026-06-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_remove_workorder_done_alter_workorder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=100),
        ),
    ]
