# Generated by Django 6.0.6 on 2026-06-28 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_asset'),
        ('workorders', '0008_alter_workorder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset'),
        ),
    ]
