# Generated by Django 6.0.6 on 2026-06-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_workorder_asset'),
        ('workrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_order', to='workrequests.workrequest'),
        ),
    ]
