# Generated by Django 6.0.6 on 2026-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_workorder_work_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='request_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='request_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
