# Generated by Django 6.0.6 on 2026-06-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_workorder_feedback_workorder_request_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='eng_description',
            field=models.TextField(blank=True),
        ),
    ]
